### ISSUE TITLE
Missing values from booking request response.

### ISSUE THREAD

**Issue by TristanBarlow** [iprosoftware/api-csharp-client#6]
There fields present in the [Push-Booking](https://github.com/iprosoftware/api-csharp-client/wiki/Push-Booking) request that are not returned by the [Booking Request](https://github.com/iprosoftware/api-csharp-client/wiki/Bookings). 

I would expect that any fields I can send to the API should also be sent by the API when I request details about that booking.
Am I missing something here, or is there an endpoint that is not listed in the documentation that I could use?

Any help would be appreciated.

**Comment by ipro-andy** [comment]
Please can you send a request through to support@ipro-software.com, so that we can answer your question in more detail
